  - hosts: hostservers
    become: yes
    become_method: sudo
    remote_user: sradhasuman88
    
    tasks:
       - name: enable UFW
         ufw:
           state: enabled
           
       - name: Allows port 8080
         ufw:
           rule: allow
           port: 8080
           proto: tcp
           
       - name: Allow port 22
         ufw:
           rule: allow
           port: 22
           proto: tcp